app/src/main/java/nl/hnogames/domoticz/GeoSettingsActivity.java, app/src/main/res/layout/activity_geo_settings.xml
https://github.com/domoticz/domoticz-android/issues/3 Fixes long translations
Resolve lint issues and deprecated methods
=> Geosettings

app/src/main/java/nl/hnogames/domoticz/GeoSettingsActivity.java, app/src/main/res/layout/activity_geo_settings.xml
https://github.com/domoticz/domoticz-android/issues/5 Fixes list to short
=> https://github.com/domoticz/domoticz-android/issues/5 Fixes list to short

app/src/main/java/nl/hnogames/domoticz/Utils/SharedPrefUtil.java
https://github.com/domoticz/domoticz-android/issues/29 Fix for app crash when there are no geofence locations or all are disabled
=> Development branch

app/src/main/java/nl/hnogames/domoticz/Containers/GraphPointInfo.java, app/src/main/java/nl/hnogames/domoticz/Fragments/Utilities.java, app/src/main/java/nl/hnogames/domoticz/UI/GraphDialog.java, app/src/main/res/layout/dialog_graph.xml, app/src/main/res/values-nl/strings.xml
Evohome zone temperatures also have a setpoint. This patch shows the setpoint on the graph.
=> Show set point on graph

app/src/main/AndroidManifest.xml
=> Add intent in manifest for quick access to app settings

app/src/main/java/nl/hnogames/domoticz/Domoticz/Domoticz.java, app/src/main/java/nl/hnogames/domoticz/Preference/Preference.java, app/src/main/java/nl/hnogames/domoticz/Utils/UsefulBits.java
Preferences - Simplify context
Add copy to clipboard in Usefullbits and apply to preferences and domoticz.java
=> Code cleanup

app/src/main/java/nl/hnogames/domoticz/Domoticz/UpdateParser.java, app/src/main/java/nl/hnogames/domoticz/Interfaces/UpdateReceiver.java, app/src/main/java/nl/hnogames/domoticz/MainActivity.java, app/src/main/java/nl/hnogames/domoticz/Preference/Preference.java, app/src/main/java/nl/hnogames/domoticz/Utils/SharedPrefUtil.java, app/src/main/res/values/strings_dashboard.xml
Enhance server update available check
Implement snackbar instead of toast
=> Enhance server update available check

app/build.gradle, app/src/main/java/nl/hnogames/domoticz/Utils/PermissionsUtil.java
Can only use lower 8 bits for requestCode #92
=> Can only use lower 8 bits for requestCode #92

app/src/main/java/nl/hnogames/domoticz/UI/TemperatureDialog.java
=> Thermostat button fix #48

app/src/main/java/nl/hnogames/domoticz/Adapters/DevicesAdapter.java
After this #107 is fully fixed
=> Fix height issue again

app/src/main/java/nl/hnogames/domoticz/GeoSettingsActivity.java, app/src/main/res/values/strings_locations.xml
Fix for when activity was ended but snackbar was not yet dismissed
Link Geofencing enable switch and notification switch
Disable Geofencing when no Geofences are enabled
=> Geosettings UX enhancement - part deux

app/src/main/java/nl/hnogames/domoticz/Utils/RequestUtil.java
RequestUtil
- Add logging
- Resolve lint issues
=> Request util code changes

app/src/main/java/nl/hnogames/domoticz/Adapters/DevicesAdapter.java, app/src/main/java/nl/hnogames/domoticz/Adapters/SceneAdapter.java, app/src/main/java/nl/hnogames/domoticz/Adapters/SwitchesAdapter.java, app/src/main/java/nl/hnogames/domoticz/Containers/DevicesInfo.java, app/src/main/java/nl/hnogames/domoticz/Domoticz/SwitchLogParser.java, app/src/main/java/nl/hnogames/domoticz/GeoSettingsActivity.java, app/src/main/java/nl/hnogames/domoticz/MainActivity.java, app/src/main/java/nl/hnogames/domoticz/Service/BootUpReceiver.java, app/src/main/java/nl/hnogames/domoticz/Utils/SharedPrefUtil.java, app/src/main/java/nl/hnogames/domoticz/Utils/UsefulBits.java
SwitchLogParser:
- Resolve lint issues by renaming
UsefulBits:
- Resolve lint issues
- Code cleanup
Remove context from date format
Change deprecated code
GeofenceSettings:
- Rename method to better explain
- Only start Geofencing on boot when it's enabled
- Move more Geofence methods to sharedPrefsUtil class
- Replace deprecated code
- Make public methods private
=> Change deprecated code & enhance Geosettings

app/src/main/java/nl/hnogames/domoticz/Adapters/WeatherAdapter.java, app/src/main/java/nl/hnogames/domoticz/Containers/Language.java, app/src/main/java/nl/hnogames/domoticz/Domoticz/Domoticz.java, app/src/main/java/nl/hnogames/domoticz/Domoticz/LanguageParser.java, app/src/main/java/nl/hnogames/domoticz/Fragments/Weather.java, app/src/main/java/nl/hnogames/domoticz/Interfaces/LanguageReceiver.java, app/src/main/java/nl/hnogames/domoticz/MainActivity.java, app/src/main/java/nl/hnogames/domoticz/Preference/Preference.java, app/src/main/java/nl/hnogames/domoticz/Utils/SharedPrefUtil.java, app/src/main/java/nl/hnogames/domoticz/Utils/UsefulBits.java, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_settings.xml
Bugfix when configInfo is null on first start up of app
New feature: language translations used from domoticz server for weather info and graphs
=> ConfigInfo bugfix and languages of domoticz server

app/src/main/java/nl/hnogames/domoticz/UI/TemperatureDialog.java, build.gradle, libs/MemorizingTrustManager/build.gradle, libs/SeekArc_library/res/drawable-mdpi/marker_background.xml, libs/SeekArc_library/res/drawable-mdpi/marker_empty.xml, libs/SeekArc_library/res/drawable-mdpi/marker_fill.xml, libs/SeekArc_library/res/drawable-mdpi/marker_foreground.xml, libs/SeekArc_library/res/values/attrs.xml, libs/SeekArc_library/src/com/triggertrap/seekarc/SeekArc.java
SeekArc, support for markers
Temp dialog code changes
Temp dialog: fix issue for when using the buttons it was possible to have half a degree over and under the max and min temp
=> Temperature set enhancements

app/src/main/java/nl/hnogames/domoticz/Service/WearMessageListenerService.java
Get error message through Domoticz helper
=> Fix for issue #189

app/src/main/java/nl/hnogames/domoticz/Adapters/DevicesAdapter.java, app/src/main/java/nl/hnogames/domoticz/PlanActivity.java, app/src/main/java/nl/hnogames/domoticz/app/DomoticzFragment.java
=> PlanActivity

app/build.gradle
=> Update Android Support libraries to 23.2.1

app/src/main/java/nl/hnogames/domoticz/Adapters/DashboardAdapter.java, app/src/main/java/nl/hnogames/domoticz/Containers/DevicesInfo.java, app/src/main/java/nl/hnogames/domoticz/Domoticz/Domoticz.java, app/src/main/java/nl/hnogames/domoticz/Fragments/Dashboard.java, app/src/main/java/nl/hnogames/domoticz/MainActivity.java, app/src/main/java/nl/hnogames/domoticz/Preference/Preference.java, app/src/main/java/nl/hnogames/domoticz/Service/TaskService.java, app/src/main/java/nl/hnogames/domoticz/Utils/UsefulBits.java, app/src/main/res/values/strings_server.xml
Fetch server config success message toast
DashboardAdapter: code cleanup
Dashboard: handle UI changes to devices local instead of fetching all data from server again
=> Alpha development

app/src/main/AndroidManifest.xml, app/src/main/java/nl/hnogames/domoticz/Widgets/WidgetIntentReceiver.java, app/src/main/java/nl/hnogames/domoticz/Widgets/WidgetProviderLarge.java, app/src/main/res/layout/widget_layout_blinds.xml, app/src/main/res/layout/widget_layout_blinds_dark.xml, wear/src/main/java/nl/hnogames/domoticz/Domoticz/Domoticz.java
This change allows a user to control blinds in Widgets and on Wear devices. This should address issue #352 and #24 partially.
=> Allow blinds control in Widget and Wear

README.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/nl/hnogames/domoticz/AutoService.java, app/src/main/res/xml/automotive_app_desc.xml
Hello,
I add an interface for android auto.
I test it on my car with https://github.com/Eselter/AA-Phenotype-Patcher (root needed).
Google may allow in the future 3rd party app on android auto or allow to publish home automation app compatible with android auto on the playstore.
=> Android auto
